### ISSUE TITLE
External-GitHub

### ISSUE THREAD

**Issue by desenvolvedorIcotrade** [philippj/SteamworksPy#10]
Parceiros/Links-patrocinados [](url)

**Comment by Gramps** [comment]
I'm not sure I understand the issue.  Can you explain?

**Comment by desenvolvedorIcotrade** [comment]
Can help! I want to create a custom space here in GitHub somehow to interact and call the Attention content creators to Register! from another platform! that pays $ by software creation apps, ads etc ...

**Comment by Gramps** [comment]
I'm not sure I understand what you're talking about or how this is related to this project.  Thus I'll close it unless there is a legitimate issue.

**Comment by desenvolvedorIcotrade** [comment]
ok no problem
