### ISSUE TITLE
I am unable to run

### ISSUE THREAD

**Issue by 2012zzw** [philippj/SteamworksPy#103]
PS D:\game>  d:; cd 'd:\game'; & 'd:\Program\Python39\python.exe' 'c:\Users\zhangziwen\.vscode-insiders\extensions\ms-python.debugpy-2024.7.11591013-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher' '56845' '--' 'd:\game\main.py'
Traceback (most recent call last):
  File "d:\game\main.py", line 4, in <module>
    steamworks = STEAMWORKS()
  File "d:\game\steamworks\__init__.py", line 51, in __init__
    self._initialize()
  File "d:\game\steamworks\__init__.py", line 91, in _initialize
    self._cdll          = CDLL(library_path) # Throw native exception in case of error
  File "d:\Program\Python39\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 127] Unable to find the specified program.
PS D:\game> 
![屏幕截图 2024-07-08 163217](https://github.com/philippj/SteamworksPy/assets/132897033/6fa0c115-41d9-44db-815e-342ace7a3e99)

**Comment by blank-repo** [comment]
Hi, I made a pypi package, should help make things easier,
as you don't need anything else.

_starting from empty folder_

- Install the package.
- create a py file in your desired folder.
- add you appid.txt
- make sure a steamclient is running and you appid is valid.
only difference from the file in your screenshot is the first line changes to:
```py
from steamworkspy.steamworks import STEAMWORKS
```

**Windows:**
```
py -m pip install steamworkspy
```

**Comment by 2012zzw** [comment]
Thanks.It's easy to run.
