### ISSUE TITLE
Documentation link not working?

### ISSUE THREAD

**Issue by dodgyville** [philippj/SteamworksPy#11]
Hi, I love your project I get a "site not found" when I use https://gramps.github.io/SteamworksForPython/

**Comment by Gramps** [comment]
Hey there.  Sorry for the late response.  Hmm, you are right.  The repo name changed about a month back but Github should have been redirecting it.

Were you following the link from the Steamworks documentation or do I have an old link somewhere?  Sounds like I need to update something.

**Comment by MasterSteelblade** [comment]
Looks like the links are in the Readme file as presented on the main page. Just created a quick pull request to fix that at #12 :)

**Comment by Gramps** [comment]
Approved and merged!  I'm sure it's wrong on the official Steamworks documentation so I'll try to contact someone about fixing that.

I should also start putting together the wiki like I have for GodotSteam.
