### ISSUE TITLE
Specified module not found

### ISSUE THREAD

**Issue by benaclejames** [philippj/SteamworksPy#17]
I'm not sure if this is a bug or something wrong with my installation but I downloaded the prebuilt dll and tried running and got this error whatever I tried.
![image](https://user-images.githubusercontent.com/11042095/59163930-c4d30200-8afe-11e9-9fcf-7f305205092b.png)

**Comment by Gramps** [comment]
Hmm, is that the only output you see?  If so then something is wrong with the steamworks.py file itself maybe the pre-compiled DLL.  I'll have to run some tests to see.

That being said, I am slowly working on a major overhaul on everything that will hopefully be released sometime this summer.

**Comment by Gramps** [comment]
New pre-compiles are available as I am starting to update and add more things.  There is also an experimental branch with newer stuff.

Are you still having the same issue?  If so, can you try new pre-compiled versions?

**Comment by Gramps** [comment]
Also you can now try the new module layout on the master branch to see if this fixed the issue.

Since this issue is really old with no updates, I will close it.  If it still plagues you, please let me know and we'll re-open it and try to solve it again!

**Comment by lautaskriptaaja** [comment]
Hello. I was having the very same issue. Windows 10, 64-bit, Python 3.7.6. Tried pretty much everything. There was no other error message besides in the original post. Was driving me crazy.

Turned out the issue was that the Python I was using was installed from Microsoft Store. The fix was as simple as to install the Python from the Python website (instead of the one installed from Microsoft Store).

**Comment by Gramps** [comment]
Huh, I wonder what the version from the Microsoft Store does differently than the installer from Python directly.  I will have to add this as a note somewhere, just in case.

**Comment by lautaskriptaaja** [comment]
I guess it has something to do with permissions, and the Microsoft Store apps are stored in Program Files/WindowsApps which requires special permissions.

**Comment by Gramps** [comment]
Ah, that make sense.  Not sure why they would do that but it is Microsoft...
