### ISSUE TITLE
is not a valid win32 application

### ISSUE THREAD

**Issue by SilentHG** [philippj/SteamworksPy#18]
Hello,
i am using visual studio 2017,
Under Linker > Input, add steam_api.lib or steam_api64.lib to Additional Dependenices.
Clean and build.
at this point i got an error of (cannot open steam_api.lib)
then i added a path in library directories in VC++ directories 
and the issue faded away and project gets build without any error
at this step
Move the steamworks.py and new compiled SteamworkPy.so or SteamworksPy.dll from the unpacked repo into your project.
You also will have to move over the libsteam_api.so, steam_api.dll, libsteam_api.dylib as well.

there is no file such as steamworkspy.dll file in unpack reso, so assumed it is the additionally provided file (Additionally, you can acquire the pre-built versions of the Linux SO files and Windows DLL files here: https://github.com/Gramps/SteamworksForPython/releases)
and i could not understand the part where you say move into your project, so moved the files into the project directory created by visual studio for the project.
and when i try to debug i get the error of project1.dll is not a valid win32 application.
if you could elaborate a bit more that will help. 
Thank you for creating this project.
Error Image: https://imgur.com/a/eZroNCE

**Comment by Gramps** [comment]
Hi there.  Hmm, can't say I use Visual Studio very often.  Mostly do everything in Linux, but let's see what we can figure out.

The DLL file should be compiled by Visual Studio and dumped into a folder somewhere.  Not sure on exactly where that would be.  Though I think the Project1.dll it is referencing is your compiled DLL file.

The part about moving the repo into your project is basically moving the steamworks.py file and your compiled DLL into the folder where you game code is.  Since it will be imported into your game script; sort of how the test stuff is arranged.

Let me know if this helps at all!

**Comment by Gramps** [comment]
If your issue is still ongoing and my advice didn't help, please let me know and we can re-open the issue!

**Comment by Nereg** [comment]
Hi! I got same problem. Here is full stacktrace :
```
Traceback (most recent call last):
  File "main.py", line 18, in <module>
    steamworks = STEAMWORKS()
  File "C:\Users\Oleg\Desktop\New folder\steamworks\__init__.py", line 50, in __init__
    self._initialize()
  File "C:\Users\Oleg\Desktop\New folder\steamworks\__init__.py", line 90, in _initialize
    self._cdll          = CDLL(library_path) # Throw native exception in case of error
  File "C:\Users\Oleg\AppData\Local\Programs\Python\Python38-32\lib\ctypes\__init__.py", line 369, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application
```
OS: Windows 10 1809 64 bit 
Python: `Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:21:23) [MSC v.1916 32 bit (Intel)] on win32`
DLL: downloaded [here](https://github.com/philippj/SteamworksPy/blob/master/redist/windows/SteamworksPy64.dll) (64 bit version)
Main.py : [from this repository](https://github.com/philippj/SteamworksPy/blob/master/examples/basic/__init__.py)
Is steam running? : yes 
File structure: https://prnt.sc/ty8y24

**Comment by Nereg** [comment]
Oh sorry I was missing Steamworks SDK libraies and replaced 64 bit version with 32 bit
