### ISSUE TITLE
Wrong architecture being detected in Steam.Init() method.

### ISSUE THREAD

**Issue by peacegiverman** [philippj/SteamworksPy#2]
Python 3.4, the expression on line 37:

`if sys.maxsize > 2**32 is False:`

always returns false, because `2**32 is False` has greater precedence than `sys.maxsize > 2**32`.

You should surround the comparison with parentheses to fix it. I.e.
`if (sys.maxsize > 2**32) is False:`

**Comment by Gramps** [comment]
Hmm, good call.  Though I feel like this was always a bad way to find the system bit size.  Will update this now though!  Cheers.
