### ISSUE TITLE
access violation reading 0x0000000000000000

### ISSUE THREAD

**Issue by codefather-labs** [philippj/SteamworksPy#20]
Traceback (most recent call last):
  File "C:/Users/root/Desktop/python_main/main.py", line 3, in <module>
    Steam.Init()
  File "C:\Users\root\Desktop\python_main\steamworks.py", line 95, in Init
    if Steam.cdll.SteamInit() == 1:
OSError: exception: access violation reading 0x0000000000000000

**Comment by Gramps** [comment]
I'm going to guess this is happening on the main branch with the pre-compiled DLL?  I too get the same issue with the master pre-compile but not on the experimental pre-compile.  I assume there is a problem with the DLL itself as the steamworks.py file is almost the same.

I will try to look into it this weekend!

**Comment by Gramps** [comment]
OK, I actually found an issue with the steamworks.py file, corrected it, then pushed it to the repo.  However, that wasn't causing the problem we were having.

What was is the missing steam_appid.txt which is required to run the library outside of the Steam client itself.  You need a text file called steam_appid.txt with 480 or your game's Steam ID in it.  Without that it crashes.

**Comment by codefather-labs** [comment]
Im working with txt file. Its not working

With c# facepunch library steam works care

**Comment by codefather-labs** [comment]
so, i need use Experimental Pre-Compiles dll?

**Comment by Gramps** [comment]
It should work.  I had no issue once I added the steam_appid.txt.  You have Steam running?  What error are you getting currently?

Either experimental or master should work.
