### ISSUE TITLE
Workshop subscribe

### ISSUE THREAD

**Issue by pistol-whip** [philippj/SteamworksPy#24]
Hello,

thanks for the awesome library.

I wanted to ask if there is any particular reason that both calls `ISteamUGC::SubscribeItem` and `ISteamUGC::UnsubscribeItem` aren't implemented at the moment and are PRs towards this accepted?

**Comment by Gramps** [comment]
Hey!  Welcome!  Honestly, I'm not sure.  Those were added as a pull request.  I haven't gotten to the UGC / Workshop stuff yet.

That being said, yes, any pull request is welcome!

**Comment by philippj** [comment]
Added that in #25

**Comment by Gramps** [comment]
Awesome!  Thanks for the pull request, sir!
