### ISSUE TITLE
Using Callbacks

### ISSUE THREAD

**Issue by Stuntm4nMike** [philippj/SteamworksPy#29]
I'm not sure how to register listeners for callbacks which seems to be important feature in Steamworks.

**Comment by Gramps** [comment]
In one of your game loops, perhaps the main loop, you need to call the Steam.runCallbacks() function.  Once that is going, you can receive them to trigger other functions.

Outside of that, I'm not fully sure as I was working on that part before everything was changed over to a legit module.  Now I am starting from scratch, so to speak, on getting those ironed out.

**Comment by Stuntm4nMike** [comment]
The thing is that in original documentation for steamworks it's said that functions acctivated on callback-event are registered through STEAM_CALLBACK macro. So I'm not sure how to register them here

**Comment by Gramps** [comment]
Yeah, that STEAM_CALLBACK is built in the SteamworksPy.cpp file not in your Python code.  You can look at the Workshop section of the module for examples on how it works:

```
def SetItemInstalledCallback(self, callback: object) -> bool:
        """Set callback for item installed
        :param callback: callable
        :return: bool
        """
        self._ItemInstalled = self._ItemInstalled_t(callback)
        self.steam._cdll.Workshop_SetItemInstalledCallback(self._ItemInstalled)
        return True
```

I believe it will call **Workshop_SetItemInstalledCallback** in your code and do whatever you script it to.

**Comment by Stuntm4nMike** [comment]
Ok, thanks

**Comment by Gramps** [comment]
Gotta do some tests with User Stats callbacks and I'll write you a more specific example!
