### ISSUE TITLE
Implementing GetAuthSessionTicket and CancelAuthTicket

### ISSUE THREAD

**Issue by lautaskriptaaja** [philippj/SteamworksPy#32]
Hello, I need to implement GetAuthSessionTicket and CancelAuthTicket. 

Any advice what to type to SteamworksPy.cpp to achieve this?

Thanks.

**Comment by Gramps** [comment]
Hey there.  This is how it was implemented in my GodotSteam library:
```
// Get an authentication ticket ID.
uint32_t Steam::getAuthSessionTicket(){
	if(SteamUser() == NULL){
		return 0;
	}
	uint32_t ticketSize = 1024;
	uint32_t *buffer = memnew_arr(uint32_t, ticketSize);
	uint32_t id = SteamUser()->GetAuthSessionTicket(buffer, ticketSize, &ticketSize);
	TicketData ticket = {id, buffer, ticketSize};
	tickets.push_back(ticket);
	return id;
}
// Cancels an auth ticket.
void Steam::cancelAuthTicket(uint32_t authTicket){
	if(SteamUser() == NULL){
		return;
	}
	for(int i = 0; i < tickets.size(); i++){
		TicketData ticket = tickets.get(i);
		if (ticket.id == authTicket){
			tickets.remove(i);
			memdelete_arr(ticket.buffer);
			break;
		}
	}
}
```
This, obviously, needs modified for Python.  Restypes and argtypes have to be added in as well.  And the Python function that matches it in the steamworks.py file.

**Comment by lautaskriptaaja** [comment]
Thanks, it helped me a lot. I played around for 20 hours too long without ultimate success.

Did something very, very dirty fix-arounds to get the id and the ticket buffer returned to python, without luck (got only `{"response":{"error":{"errorcode":3,"errordesc":"Invalid parameter"}}}` as feedback from ISteamUserAuth/AuthenticateUserTicket/ when I tried to validate the ticket from web api with python.requests)

The best hack I came up with was making GetAuthSessionTicket() to return a char*, which was basically "`{id};{buffer}`" and let python handle the rest. To get to that result, I created `char result[50000];`, to which I strcatted the id, ";", and buffer (as strings). I got the strings with `sprintf(result, "%lu", id);` and looped through the buffer with 
```
for (int i = 0; i < ticketSize; i++) {
    char string_to_add[50];
    sprintf(string_to_add, "%lx", buffer[i]); //create hex string from the value
    strcat(result, string_to_add);
}
```
On python side, I splitted the response, and tried many, many ways to validate it with requests without successing, only receiving "Invalid parameter". 
Most commonly I tried

```
response = requests.get("https://partner.steam-api.com/ISteamUserAuth/AuthenticateUserTicket/v1/", {"key": "FB957F29349XXXXXXXXXXB5BA76EFBD3", "appid":1254XXX, "ticket":ticket_to_send})
```

Any advice what I'm possibly doing wrong? It really got me exhausted, didn't believe I'll spend over 20 hours at this.

ps. this is the way I got the id and the buffer

```
uint32 ticketSize = 1024;
uint32_t* buffer = (uint32_t*) malloc(ticketSize * sizeof(uint32_t));
HAuthTicket id = SteamUser()->GetAuthSessionTicket(buffer, ticketSize, &ticketSize);
```

**Comment by Gramps** [comment]
Hmm, I haven't really tinkered much with the auth ticket stuff but I have a similar issue still open in my GodotSteam module (quite outstanding still).  I will take some of what you did and see what I can figure out as well.

Also, they updated Steamworks to 1.48 and apparently big updates to the flat version of the API which might help out.  I haven't really dug into it too much but am doing so tomorrow so I'll add this to my plate as well.

Hope to have something more by Monday!

**Comment by Gramps** [comment]
Got bogged down by some additions to make things a bit more efficient so my response is delayed a bit.  However, will report back soon.

**Comment by reciate** [comment]
If you're still interested, I just finished my implementation of GetAuthSessionTicket which I verified to be working.

**Comment by Gramps** [comment]
I think that'd be quite useful.  Can you issue a pull request?

**Comment by Cussa** [comment]
Hello guys. Is there any progress in this issue? I am quite interested in the `GetAuthSessionTicket` and I would like to know if there is any estimation about it. @reciate any news? 😄

**Comment by reciate** [comment]
@Cussa I sent a pull request for this quite a while ago: https://github.com/philippj/SteamworksPy/pull/48

@Gramps would appreciate if this is closed now.

**Comment by philippj** [comment]
Close as implemented via PR #48

**Comment by Cussa** [comment]
@philippj @Gramps  any possibility to release a new version with this? I saw that it was merged, but there is no new release for that. Thanks in advance!

**Comment by reciate** [comment]
@Cussa https://github.com/philippj/SteamworksPy/blob/master/redist/windows/SteamworksPy64.dll
