### ISSUE TITLE
Problem with util being interpreted as part of ctypes

### ISSUE THREAD

**Issue by sudasana** [philippj/SteamworksPy#39]
I just started using SteamworksPy, and I was only able to get everything running after I made a very small change in the main `__init__.py` file. Initially my attempt to import the library failed:

```
File "\steamworks\__init__.py", line 40, in STEAMWORKS
    _arch = util.get_arch()
AttributeError: module 'ctypes.util' has no attribute 'get_arch'
```

I fixed this simply by changing the steamworks `util` into something unique:

`import steamworks.util 		as s_util`

and

`_arch = s_util.get_arch()`

I'm not sure why the interpreter why understanding util as part of ctypes, but this fixed it and everything looks be be initializing fine now.

**Comment by Gramps** [comment]
Huh, that's pretty odd.  I'll check into it!  Thanks for letting me know!

**Comment by sudasana** [comment]
No problem, thanks for the project!
