### ISSUE TITLE
No attribute 'RunCallbacks'

### ISSUE THREAD

**Issue by Subserial** [philippj/SteamworksPy#41]
I'm attempting to run CreateLobby(), and other issues say to run RunCallbacks() to at least execute a callback (I'm not sure where to go from here). The function does not seem to exist after `steamworks.initialize()`. Tested with both the precompiled DLL and compiling locally for version 1.6.2. 

```
>>> steamworks.run_callbacks()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "V:\Code\steamworks\steamworks\__init__.py", line 193, in run_callbacks
    self.RunCallbacks()
AttributeError: 'STEAMWORKS' object has no attribute 'RunCallbacks'
```

**Comment by Gramps** [comment]
Yep, I do not believe RunCallbacks is a function currently.  However, it is needed for all lobby functions to work correctly.

That being said, my next large update contains all the missing callback functionality and should be uploaded in about two weeks.  It will also contain lots more functions in general and frameworks for ones I can't quite figure out (mostly passing back dictionary and arrays).

**Comment by Subserial** [comment]
Alright, thanks for the quick reply, I thought I was going insane in the compile process. Eagerly waiting until then!

**Comment by Gramps** [comment]
No problem!  Yeah, it was supposed to be finished a week or so ago but I am a bit more swamped than expected.
