### ISSUE TITLE
How to upload mode to workshop using this API? 

### ISSUE THREAD

**Issue by Chenger1** [philippj/SteamworksPy#45]
Is there any ways to work with workshop? For example i have a simple mod manager and want to upload new mod using API. Can i do it? 
In official documentation there is information that i have to become a Steamworks partner, etc. 
I found "Steam Workshop Implementation Guide" which includes information about it but it provides API for C++, not Python. And there is a question about partnership with Steam as well.

**Comment by Gramps** [comment]
Currently there are a few features for Workshop/UGC.  The developers of Switch Cars actually added though features with a pull request a while back.  There are a ton more that I am (slowly) adding in to an update I was working on.

Yes, you'll need to be a Steamworks partner and have purchased an app license to use it.  The examples they have for C++ will be somewhat similar to Python except you are just going to use the functions in the module.

**Comment by Chenger1** [comment]
Got it. Thank you.
