### ISSUE TITLE
Login without running steam ?

### ISSUE THREAD

**Issue by Nereg** [philippj/SteamworksPy#47]
Hello ! I wondered if your library can wotk without steam installed and logged in on computer. Like I have account login and password why I can just login?

**Comment by philippj** [comment]
Steamworks is a way of interacting with Steam and Steam services from your game or application. 

What you seem to want is an emulated Steam client. Steamworks does not provide this nor does this library.

**Comment by Nereg** [comment]
Oh ok thanks! And if you know any please send some here because I couldn't find any.
