### ISSUE TITLE
Typo in Workshop_UnsubscribeItem

### ISSUE THREAD

**Issue by rimpy-custom** [philippj/SteamworksPy#59]
https://github.com/philippj/SteamworksPy/blob/eac06c6821d8e7f579f971285f4475a8c87cca12/steamworks/interfaces/workshop.py#L146

Probably should be:
self.steam.Workshop_Un**s**ubscribeItem(published_file_id)
"s" is missing.

**Comment by Gramps** [comment]
That is definitely a typo.  Good find!

**Comment by philippj** [comment]
Fixed in 89baefc
