### ISSUE TITLE
SteamworsPy.dll missing from master

### ISSUE THREAD

**Issue by rimpy-custom** [philippj/SteamworksPy#60]
May I ask for a precompiled SteamworsPy.dll to be added to the master. Just a feature request.

**Comment by philippj** [comment]
You can find one at https://github.com/philippj/SteamworksPy/tree/master/redist/windows

**Comment by rimpy-custom** [comment]
Yeap and it works great, but for compatibility with x86 OS SteamworsPy.dll is needed. The same for linux - SteamworsPy.so. Have found instruction in FAQ how to compile myself, but didn;t try yet.

**Comment by rimpy-custom** [comment]
That was an easy. Sorry for disturbing you. Compilled fine.
