### ISSUE TITLE
[LINUX] libsteam_api.so not found

### ISSUE THREAD

**Issue by rimpy-custom** [philippj/SteamworksPy#61]
Have tried to compile  SteamworksPy on Debian 10, process was successful. But when I try to use it, I get error:
`libsteam_api.so: cannot open shared object file: No such file or directory`
`ldd SteamworksPy.so` return this:
`libsteam_api.so => not found`
But it is in the same folder. next to SteamworksPy.so file.

`ldd SteamworksPy.so` from precompiled 1.6.1 release also has the same issue.

**Comment by rimpy-custom** [comment]
Ok, fixed that with adding to the end of makefile: `-Wl,-rpath=.`:
`g++ -std=c++11 -o SteamworksPy.so -shared -fPIC SteamworksPy.cpp -l steam_api -L. -Wl,-rpath=.`

**Comment by Cussa** [comment]
Hello, one question: is it possible to provide the Linux compiled version, like we have for windows?
The latest release just have the windows 64 dll.

**Comment by danlexo** [comment]
Just to note, if `-Wl,-rpath=.` flag is not set then `LD_LIBRARY_PATH` environment variable needs to be set to where `libsteam_api.so` is located

**Comment by vu1canic** [comment]
PR works for at least for me

**Comment by philippj** [comment]
Resolved by #72
