### ISSUE TITLE
I cannot get this installed and working

### ISSUE THREAD

**Issue by theradman221** [philippj/SteamworksPy#66]
I've been trying to get this module working for about 6 hours now. I've followed the steps at https://philippj.github.io/SteamworksPy/
Right now I'm just trying to get the module working with a blank main.py without getting it working with the actual project, but all I'm getting is 
Traceback (most recent call last):
  File "D:\desktop\KingdomsDev\SteamworksPy-1.6.2\main.py", line 3, in <module>
    steamworks.initialize()
  File "D:\desktop\KingdomsDev\SteamworksPy-1.6.2\steamworks\__init__.py", line 147, in initialize
    result = self._cdll.SteamInit()
OSError: exception: access violation reading 0x0000000000000000
Also, it mentions a Steamworks.py file at the end of the installation and there is not one anywhere that I can find.
I would really appreciate any help, I'm not sure what I'm doing wrong at this point.
Edit,
Realized it would probably also be important to note that I'm trying to install it using the precompiled dll for windows 64 bit, from the version 1.6.2 release, with the 1.48a SDK

**Comment by philippj** [comment]
Hi.

Place the latest precompiles from https://github.com/philippj/SteamworksPy/tree/master/redist/windows in your working directory. Additionally you need the steam_api.dll and the corresponding steam_api.lib from Steamworks to be in the same directory.

**Comment by theradman221** [comment]
I did this and I'm still getting that same error.
I have SteamworksPy64.dll, steam_api64.lib and .dll, as well as my steam_appid.txt all in the same directory as the main.py.
I also have the steamworks folder there.
I'm sorry if this seems stupid, but what am I missing? I've tried using the steam_api.dll and .lib from the redistributable bin and without it. 
Again that error is 
Traceback (most recent call last):
  File "D:\desktop\KingdomsDev\steampy attempt\main.py", line 3, in <module>
    steamworks.initialize()
  File "D:\desktop\KingdomsDev\steampy attempt\steamworks\__init__.py", line 147, in initialize
    result = self._cdll.SteamInit()
OSError: exception: access violation reading 0x0000000000000000

**Comment by philippj** [comment]
Is your Steam Client running and you are logged in?

**Comment by theradman221** [comment]
yes

**Comment by philippj** [comment]
Which Windows version and architecture are you on?

**Comment by theradman221** [comment]
I'm using windows 10 Home, version 10.0.19041 Build 19041
The architecture is 64 bit.

**Comment by philippj** [comment]
I can not reproduce your issue on any of my machines on a similar Windows build.

**Comment by theradman221** [comment]
weird.

**Comment by theradman221** [comment]
Do you think you could share a complete directory that works for you with me?
I'm not sure whether it's my computer, or just me putting a file in the wrong place.
Thanks for your help!

**Comment by philippj** [comment]
This is a fully working example:
[SteamworksPyTest.zip](https://github.com/philippj/SteamworksPy/files/6229666/SteamworksPyTest.zip)

**Comment by theradman221** [comment]
thanks, it seems to be working as long as I use your example. I think that the problem was either one of the dll's or I may not have been importing quite right. Thanks again for your help!

**Comment by theradman221** [comment]
I may have found the thing causing all my stress, I was using the app id for the game we're developing, and when I use the 480 one instead it doesn't give me the error...

**Comment by blank-repo** [comment]
> This is a fully working example: [SteamworksPyTest.zip](https://github.com/philippj/SteamworksPy/files/6229666/SteamworksPyTest.zip)

:/ I am having so much trouble getting this to work, 
I eventually find this, 
download the test zip, 
run it, 
works.

Okay... not sure what I'm doing wrong but this zip is a godsend.
Thank you 🥇
