### ISSUE TITLE
GetFriendCount() error

### ISSUE THREAD

**Issue by NikitaYezhov** [philippj/SteamworksPy#67]
friends_count = steamworks.Friends.GetFriendCount(0x10)
  File "c:\Visual Code\python\Ark-steam\steamworks\interfaces\friends.py", line 23, in GetFriendCount
    return self.steam.GetFriendCount(flag.value)
AttributeError: 'int' object has no attribute 'value'

**Comment by NikitaYezhov** [comment]
![image](https://user-images.githubusercontent.com/53224795/115241779-a0a0cd00-a13a-11eb-9449-c0aed33b94d2.png)

**Comment by philippj** [comment]
Hi,

The method works as expected and documented. You need to pass an enum of type `FriendFlags`.

```py
[...]
from steamworks import STEAMWORKS
from steamworks.enums import FriendFlags
[...]
friend_count: int = steamworks.Friends.GetFriendCount(FriendFlags.ALL)
[...]
```

**Comment by NikitaYezhov** [comment]
Thanks. Can you tell me one thing? When I run it while on the game server, it showed me 24 players, but its false. Steam servers browser says only about 13 people

**Comment by philippj** [comment]
The method returns you the amount of Stream friends currently online on Steam. To check player counts you need to use Steams A2S protocol or the Steam Web API.
