### ISSUE TITLE
/usr/bin/ld: cannot find -lsteam_api

### ISSUE THREAD

**Issue by peacegiverman** [philippj/SteamworksPy#7]
Ubuntu Trusty (12.04), extracted the Steamworks SDK according to instructions, but `g++` could not find it. I had to add the `-L` flag to the compile line so that it would include the local directory like this:

    g++ -std=c++11 -o SteamworksPy.so -shared -fPIC SteamworksPy.cpp -l steam_api -L.

I suggest adding this to the makefile, or adding a FAQ comment to the readme so people know what to do if they get the same error.

**Comment by Gramps** [comment]
Yeah, that started happening at some point recently but previously was not an issue.  I think it had something to do with how Steam installs in more current versions, but I'm not totally sure.  Will update the README with this.  Cheers!
