### ISSUE TITLE
Subscribing to a mod or so ?

### ISSUE THREAD

**Issue by dlartigu** [philippj/SteamworksPy#80]
Hello, I wonder if your API provide a way to subscribe to somethiong like a mod ?
I mean, like if somebody click on a link to a mod but instead of opening the web page it subscribe to it.
Thanks a lot!

**Comment by philippj** [comment]
That can be done through the SteamUGC interface

**Comment by dlartigu** [comment]
Okay thanks for answering!

**Comment by dlartigu** [comment]
After some month I still can't find a way to do so. I might be really blind! 
Where is the SteamUGC ?
Should I use the subscribeItem method ? 
Thanks a lot

**Comment by philippj** [comment]
Hi, you can interface with the Steam UGC interface through the `SteamWorkshop` class.

For example:
```py
...
steamworks = STEAMWORKS()
...

steamworks.Workshop.SubscribeItem(published_file_id, callback)

```
