### ISSUE TITLE
Unable to run basic example, getting Error 127

### ISSUE THREAD

**Issue by bigwhoopgames** [philippj/SteamworksPy#97]
When I run the 'basic' example I get the following errors:

This is using the precompiled SteamworksPy64.dll

The directory contains the following:

steamworks (folder from repo all of it)
steam_api64.dll
SteamworksPy64.dll
steam_api64.lib
__init__.py
steam_appid.txt

Tried with both python 3.12 and 3.11

Outputs the following:
![image](https://github.com/philippj/SteamworksPy/assets/72057030/be63ef72-5930-4729-b2cc-b5e4b8b2023f)

C:/Users/Derp/AppData/Local/Programs/Python/Python312/python.exe c:/Users/Derp/Desktop/teststeam/__init__.py
Traceback (most recent call last):
  File "c:\Users\Derp\Desktop\teststeam\__init__.py", line 22, in <module>
    steamworks = STEAMWORKS()
                 ^^^^^^^^^^^^
  File "c:\Users\Derp\Desktop\teststeam\steamworks\__init__.py", line 51, in __init__
    self._initialize()
  File "c:\Users\Derp\Desktop\teststeam\steamworks\__init__.py", line 91, in _initialize
    self._cdll          = CDLL(library_path) # Throw native exception in case of error
                   ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Derp\AppData\Local\Programs\Python\Python312\Lib\ctypes\__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 127] The specified procedure could not be found

**Comment by bigwhoopgames** [comment]
Update:

I was able to compile using the SDK 1.55 version however the example still does not run correctly.

Below is the output using the newly compiled version:

C:\Users\Derp\Desktop\teststeam>python __init__.py
Traceback (most recent call last):
  File "C:\Users\Derp\Desktop\teststeam\__init__.py", line 33, in <module>
    steamworks.initialize() # This method has to be called in order for the wrapper to become functional!
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Derp\Desktop\teststeam\steamworks\__init__.py", line 149, in initialize
    result = self._cdll.SteamInit()
             ^^^^^^^^^^^^^^^^^^^^^^
OSError: exception: access violation reading 0x0000000000000000

**Comment by RhysF98** [comment]
I've got the same issue with the access violation message, tried using V1.65 and V1.64 of SteamworksPy, no luck so far

**Comment by RhysF98** [comment]
Figured out what was causing it for me, might be the same issue you're having. You need to have the corresponding game in your steam library as the ID you have in your steam_appid.txt file. If you don't have that game in the library of the account you are logged in as, it will crash out with the access violation error

**Comment by bigwhoopgames** [comment]
> Figured out what was causing it for me, might be the same issue you're having. You need to have the corresponding game in your steam library as the ID you have in your steam_appid.txt file. If you don't have that game in the library of the account you are logged in as, it will crash out with the access violation error

Thanks so much! This fix the issue. I will close this, however I will leave the other issue open since compiling using the latest 1.58 SDK still does not work.
